### ISSUE TITLE
Uncaught TypeError: ((m.event.special[e.origType] || (intermediate value)).handle || e.handler).apply is not a function

### ISSUE THREAD

**Issue by zixtor** [phpmyadmin/phpmyadmin#11860]
Uncaught TypeError: ((m.event.special[e.origType] || (intermediate value)).handle || e.handler).apply is not a function

This report is related to user submitted report [#17320](https://reports.phpmyadmin.net/reports/view/17320) on the phpmyadmin error reporting server.

**Comment by zixtor** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |TypeError: e.handler.apply is not a function
 Exception Type |js
 Link | [Report#18174](https://reports.phpmyadmin.net/reports/view/18174)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by zixtor** [comment]
To reproduce: Go to table->search, switch to "zoom search" tab, switch back to "table search" tab, press any key. Introduced in https://github.com/phpmyadmin/phpmyadmin/commit/d03c3adff44ab11818023d3f6ba1419b8fcd11b6
